version: "3"

services:
  nginx:
    image: frontbear/fastnginx:1.13.11.0
    volumes:
      - vhosts:/usr/local/nginx/vhosts
    ports:
      - "80:80"
      - "443:443"
    networks:
      - nginx
      - php
      - redis
      - gitbucket
    depends_on:
      - php
      - redis
      - gitbucket

  php:
    image: frontbear/fastphp:7.16.0
    volumes:
      - vhosts:/usr/local/nginx/vhosts
    ports:
      - "9000:9000"
    networks:
      - nginx
      - php
      - redis

  redis:
    image: frontbear/fastredis:3.2.11.1
    ports:
      - "6379:6379"
    networks:
      - redis

  gitbucket:
    image: frontbear/gitbucket:4.23.0.1
    env_file:
      - ./gitbucket.env
    ports:
      - "8080:8080"
      - "29418:29418"
    networks:
      - gitbucket

networks:
  nginx:
    driver: bridge
  php:
    driver: bridge
  redis:
    driver: bridge
  gitbucket:
    driver: bridge

volumes:
  vhosts:
    driver: local
